package ru.skypro.homework.repository;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
import ru.skypro.homework.model.entity.ImageEntity;

import java.time.LocalDateTime;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

@DataJpaTest
class ImageRepositoryTest {

    @Autowired
    private TestEntityManager entityManager;

    @Autowired
    private ImageRepository imageRepository;

    @Test
    void findByFilePath_WhenImageExists_ShouldReturnImage() {
        // Given
        ImageEntity imageEntity = createTestImageEntity("/images/test.jpg");
        entityManager.persistAndFlush(imageEntity);

        // When
        Optional<ImageEntity> result = imageRepository.findByFilePath("/images/test.jpg");

        // Then
        assertTrue(result.isPresent());
        assertEquals("/images/test.jpg", result.get().getFilePath());
    }

    @Test
    void existsByFilePath_WhenImageExists_ShouldReturnTrue() {
        // Given
        ImageEntity imageEntity = createTestImageEntity("/images/exists.jpg");
        entityManager.persistAndFlush(imageEntity);

        // When
        boolean exists = imageRepository.existsByFilePath("/images/exists.jpg");

        // Then
        assertTrue(exists);
    }

    @Test
    void deleteByFilePath_ShouldDeleteImage() {
        // Given
        ImageEntity imageEntity = createTestImageEntity("/images/delete.jpg");
        entityManager.persistAndFlush(imageEntity);

        // When
        imageRepository.deleteByFilePath("/images/delete.jpg");
        entityManager.flush();

        // Then
        assertFalse(imageRepository.existsByFilePath("/images/delete.jpg"));
    }

    @Test
    void save_ShouldSetAutoGeneratedId() {
        // Given
        ImageEntity imageEntity = createTestImageEntity("/images/new.jpg");

        // When
        ImageEntity saved = imageRepository.save(imageEntity);

        // Then
        assertNotNull(saved.getId());
        assertTrue(saved.getId() > 0);
    }

    private ImageEntity createTestImageEntity(String filePath) {
        ImageEntity imageEntity = new ImageEntity();
        imageEntity.setFilePath(filePath);
        imageEntity.setContentType("image/jpeg");
        imageEntity.setFileSize(1024L);
        imageEntity.setOriginalFileName("test.jpg");
        imageEntity.setCreatedAt(LocalDateTime.now());
        return imageEntity;
    }

}